# -*- coding: utf-8 -*-
"""worldweatherrepositry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ER0sXslWUKK8G-ln4a8mMvhs9hHHEVNn
"""

# Import the dataset
data = pd.read_csv("/content/GlobalWeatherRepository.csv")

import pandas as pd
import matplotlib.pyplot as plt

# Display the first 5 rows
print(data.head())

# Optionally: Display some basic statistics or visualize the data
data.describe()

# If it's suitable for a plot:
data.plot()
plt.show()